site_name: Custodian

theme:
  name: "material"

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Quick Installation: starting/installation.md
    - Basic Tutorial: starting/tutorial.md
  - Concept:
    - Overview: concept/overview.md
    - Components: concept/components.md
  - Roadmap:
    - Future: roadmap/future.md
    - Releases Notes: roadmap/releaseNotes.md    
  - Reference:
    - Glossary: reference/glossary.md
